 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/anki_decks", type: :request do
  
  # AnkiDeck. As you add validations to AnkiDeck, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AnkiDeck.create! valid_attributes
      get anki_decks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      anki_deck = AnkiDeck.create! valid_attributes
      get anki_deck_url(anki_deck)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_anki_deck_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      anki_deck = AnkiDeck.create! valid_attributes
      get edit_anki_deck_url(anki_deck)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AnkiDeck" do
        expect {
          post anki_decks_url, params: { anki_deck: valid_attributes }
        }.to change(AnkiDeck, :count).by(1)
      end

      it "redirects to the created anki_deck" do
        post anki_decks_url, params: { anki_deck: valid_attributes }
        expect(response).to redirect_to(anki_deck_url(AnkiDeck.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AnkiDeck" do
        expect {
          post anki_decks_url, params: { anki_deck: invalid_attributes }
        }.to change(AnkiDeck, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post anki_decks_url, params: { anki_deck: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested anki_deck" do
        anki_deck = AnkiDeck.create! valid_attributes
        patch anki_deck_url(anki_deck), params: { anki_deck: new_attributes }
        anki_deck.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the anki_deck" do
        anki_deck = AnkiDeck.create! valid_attributes
        patch anki_deck_url(anki_deck), params: { anki_deck: new_attributes }
        anki_deck.reload
        expect(response).to redirect_to(anki_deck_url(anki_deck))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        anki_deck = AnkiDeck.create! valid_attributes
        patch anki_deck_url(anki_deck), params: { anki_deck: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested anki_deck" do
      anki_deck = AnkiDeck.create! valid_attributes
      expect {
        delete anki_deck_url(anki_deck)
      }.to change(AnkiDeck, :count).by(-1)
    end

    it "redirects to the anki_decks list" do
      anki_deck = AnkiDeck.create! valid_attributes
      delete anki_deck_url(anki_deck)
      expect(response).to redirect_to(anki_decks_url)
    end
  end
end
