 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/weights", type: :request do
  
  # Weight. As you add validations to Weight, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Weight.create! valid_attributes
      get weights_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      weight = Weight.create! valid_attributes
      get weight_url(weight)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_weight_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      weight = Weight.create! valid_attributes
      get edit_weight_url(weight)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Weight" do
        expect {
          post weights_url, params: { weight: valid_attributes }
        }.to change(Weight, :count).by(1)
      end

      it "redirects to the created weight" do
        post weights_url, params: { weight: valid_attributes }
        expect(response).to redirect_to(weight_url(Weight.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Weight" do
        expect {
          post weights_url, params: { weight: invalid_attributes }
        }.to change(Weight, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post weights_url, params: { weight: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested weight" do
        weight = Weight.create! valid_attributes
        patch weight_url(weight), params: { weight: new_attributes }
        weight.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the weight" do
        weight = Weight.create! valid_attributes
        patch weight_url(weight), params: { weight: new_attributes }
        weight.reload
        expect(response).to redirect_to(weight_url(weight))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        weight = Weight.create! valid_attributes
        patch weight_url(weight), params: { weight: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested weight" do
      weight = Weight.create! valid_attributes
      expect {
        delete weight_url(weight)
      }.to change(Weight, :count).by(-1)
    end

    it "redirects to the weights list" do
      weight = Weight.create! valid_attributes
      delete weight_url(weight)
      expect(response).to redirect_to(weights_url)
    end
  end
end
